### ISSUE TITLE
request for project information

### ISSUE THREAD

**Issue by madsonic** [CS2103JAN2018-T15-B1/main#12]
I would want you to mention the following in your **Developer guide**
1. For each team member what are the features (major and minor) you are proposing?
2. Within the scope of the project, how does it fit in (just a one or 2 line summary)
Please do this by end of day Monday 19 March.

**Comment by qinghao1** [comment]
See https://github.com/CS2103JAN2018-T15-B1/main/blob/v1.1/docs/DeveloperGuide.adoc#feature-contribution
