### ISSUE TITLE
Product names have to be unique (excluding deleted products)

### ISSUE THREAD

**Issue by lowjiajin** [CS2103JAN2018-T15-B1/main#75]
To ensure integrity of recommender, needed to support future functionality of not recommending products that a person has already bought.

**Comment by qinghao1** [comment]
@YingxuH there should be a duplicateproductexception right

**Comment by YingxuH** [comment]
Yah it has, under product/exceptions. Fixed the bug at 61ab754ef89ed09e3a2cc08c7f14a564f18a9052.
